language: swift
osx_image: xcode12.2

before_install:
 - echo $PWD
 - java -jar Vendor/wiremock-standalone-2.23.2.jar --port 9999 --verbose
 - gem install fastlane --no-document

install: true

script:
 - fastlane scan --scheme StarWarsInfoUITests -d 'platform=iOS Simulator,name=iPhone 12,OS=14.2' 
